---
title: "KMER"
output: html_document
date: "2026-03-09"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(tidyverse)
library(scales)
```

```{r}
source("functions.R")
```


```{r}
numReads = 27000000
gridsearchDir = "../output/plotting_data/quality/dna/"
kmerDir = paste0(gridsearchDir, "KMER/")
plotsDir = paste0(gridsearchDir, "plots/")
extType = ".jpg"


```

```{r}

k2Plot = {}

k2Map <- list()

for (k in seq(from = 12, to = 30, by = 2)) {
  kmer <- read_tsv(paste0(kmerDir, "k_", k, ".txt")) %>%
    mutate(geneSetSize = str_count(gene, ","))
  
  #leastUniqueKmers = rbind(leastUniqueKmers, kmer %>% arrange(desc(geneSetSize)) %>% head(10) %>% mutate(k = k)) 

  k2Map[[as.character(k)]] <- kmer
}

for(k in seq(from = 12, to = 30, by = 5)){
  kmer = read_tsv(paste0(kmerDir, "k_", k,".txt")) %>% mutate(geneSetSize = str_count(gene, ",")) 
  k2Map[k] = kmer

  p = kmer %>% ggplot(aes(x = geneSetSize)) +
  geom_histogram() +
  scale_y_log10(labels = scales::label_number(scale_cut = scales::cut_short_scale())) +
  themeForSaving() +
  labs(title = "How many Genes Kmers are mapped to",
       subtitle = paste("K =", k))
  print(p)
  k2Plot[k] = 
}







```

```{r}
tmpKMap = as.data.frame(k2Map[12])

tmpKMap %>% arrange((geneSetSize))
```

```{r}
for (k in names(k2Map)) {
  
  df = k2Map[[k]]
  p = df %>% ggplot(aes(x = geneSetSize)) +
  geom_histogram() +
  scale_y_continuous(
    trans = "log10",
    labels = scales::label_number(scale_cut = scales::cut_short_scale())
  ) +
  themeForSaving() +
  labs(title = "How many Genes Kmers are mapped to",
       subtitle = paste("K =", k))
  print(p)
}



```

```{r}
counts_long <- map_dfr(seq(from = 12, to = 30, by = 2), function(k) {
  read_tsv(paste0(kmerDir, "k_", k, ".txt"), show_col_types = FALSE) %>%
    mutate(
      geneSetSize = str_count(gene, ","),
      k = k
    )
}) %>%
  count(k, geneSetSize) %>%
  pivot_wider(
    names_from = k,
    values_from = n,
    values_fill = 0
  ) %>%
  pivot_longer(-geneSetSize, names_to = "k", values_to = "count") %>%
  group_by(k) %>%
  mutate(total_kmers = sum(count)) %>%
  ungroup()

```


```{r}




p = counts_long %>% 
ggplot(aes(x = geneSetSize, y = count, color = k)) +
  geom_line() +
  scale_y_continuous(
    transform = "log10",
    breaks = 10^(0:6),
    labels = scales::label_number(scale_cut = scales::cut_short_scale())
    ) +
  themeForSaving() +
  labs(
    title = "Distribution of Gene Mapping per k-mer",
    x = "Number of genes a k-mer maps to",
    y = "Number of k-mers"
  )+
  theme(legend.position = "right", legend.justification ="center") +
  coord_cartesian(ylim = c(1,1000000))

savePlotReport(paste0("../output/finalplots_real/kmerDistribution_dna", extType), p)
```

```{r}
counts_long %>% group_by(k) %>% summarise(totalCount = mean(total_kmers)) %>% 
  ggplot(aes(x = k, y = totalCount)) +
  geom_col() +
  themeForSaving() +
  scale_y_continuous(labels = scales::label_number(scale_cut = scales::cut_short_scale())) +
  labs(title = "Number of Distinct K-mers in Reference Index per k")
```



### TOTAL BARPLOT

```{r}
get_total_kmers <- function(base_dir, mode_label) {
  kmerDir <- paste0(base_dir, mode_label, "/KMER/")
  
  map_dfr(seq(from = 12, to = 30, by = 2), function(k) {
    read_tsv(paste0(kmerDir, "k_", k, ".txt"), show_col_types = FALSE) %>%
      mutate(
        geneSetSize = str_count(gene, ","),
        k = k
      )
  }) %>%
    count(k, geneSetSize) %>%
    group_by(k) %>%
    summarise(total_kmers = sum(n), .groups = "drop") %>%
    mutate(mode = mode_label)
}

base_dir = "../output/plotting_data/quality/"
total_dna = get_total_kmers(base_dir, "dna")
total_rna = get_total_kmers(base_dir, "rna")

total_kmers_df <- bind_rows(total_dna, total_rna)
```

```{r}
head(total_kmers_df)
```


```{r}
p = total_kmers_df %>% mutate(mode = toupper(mode)) %>%
  filter(k %% 2 == 0) %>%
  ggplot(aes( x = factor(k), y = total_kmers, fill = mode)) +
  geom_col(position = position_dodge(width = 0.5)) +
  themeForSaving() +
  scale_y_continuous(labels = scales::label_number(scale_cut = scales::cut_short_scale())) +
  labs(title = "Number of Distinct K-mers in Reference Index", x = "K-mer Length", y = "Size of K-mer index", fill = "Mode") +
  theme(legend.position = "bottom", legend.justification = "center")

savePlotReport("../output/finalplots_real/kmerMapSize.jpg", p)
```

