---
title: "Timing"
output: html_document
date: "2026-03-04"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(tidyverse)
library(scales)
```

```{r}
themeForSaving <- function() {
  theme(
    text = element_text(size = 14),
    axis.text.x = element_text(angle = 0, hjust = 1, size = 12),
    axis.text.y = element_text(size = 12),
    axis.title = element_text(size = 14),
    plot.title = element_text(size = 18, face = "bold"),
    plot.subtitle = element_text(size = 14),
    legend.position = c(0.98, 0.5),
    legend.justification = c(1, 1),
    legend.background = element_rect(fill = "white", colour = "grey80"),
    legend.text = element_text(size = 12),
    legend.title = element_blank()
  )
}

savePlotReport <- function(filepath, p){
  ggsave(filepath, p, width = 2100, height = 1050, units = "px")
}


```


```{r}
numReads = 27000000
gridsearchDir = "../output/plotting_data/quality/"
plotsDir = paste0(gridsearchDir, "plots/")
extType = ".jpg"


```

```{r}
readVerbose <- function(path){
  tmp = read_delim(path, delim = ": ", 
                    col_names = c("cmd", "value")) %>% 
  mutate(cmd = str_replace_all(cmd, "([\n\t])", ""))
  return(tmp)
}

parse_elapsed <- function(x) {
  parts <- strsplit(x, ":")
  sapply(parts, function(p) {
    mins <- as.numeric(p[1])
    secs <- as.numeric(p[2])
    mins * 60 + secs
  })
}

getMaxResSize <- function(verboseDF){
  return(as.numeric((verboseDF %>% filter(cmd == "Maximum resident set size (kbytes)") )$value))
}

readTiming <- function(typeStr){
  df = read_tsv(paste0(gridsearchDir, typeStr, "/time_summary.tsv"),
                         col_types = cols(elapsed = col_character())) %>% 
  mutate(mode = pair_mode,
         elapsed_sec = parse_elapsed(elapsed),
         max_rss_b = max_rss_kb * 1024,
         molecule = typeStr) %>% 
  select(-pair_mode)
  return(df)
}


```


```{r}
timing_dna = readTiming("dna") 
timing_rna = readTiming("rna")

timingSummary = rbind(timing_dna, timing_rna) %>% 
  mutate(linetype = paste(molecule, mode))

custom_cols <- c(
  "dna and" = "#3d348b",   
  "dna or"  = "#7678ed",   
  "rna and" = "#f35b04",   
  "rna or"  = "#f18701"    
)

```


```{r}


plotMetric("or", elapsed_sec, identity, df = timingSummary)
plotMetric("or", max_rss_b, identity, df = timingSummary, scaleFunc = scales::label_bytes(accuracy = 0.01))

```

```{r}
plotRunTimeFixedValue <- function(value1, metric1, xMetric, df = timingSummary, metric2=NA, value2=NA){
  xString = metricString <- deparse(substitute(xMetric))
  filterString = paste(deparse(substitute(metric1)), "=", value1)
  if(!is.na(value2)) 
    filterString = paste(filterString, "and", deparse(substitute(metric2)), "=", value2)

  
  df = df %>% 
    filter({{metric1}} == value1 &
             (if(!is.na(value2)) {{metric2}} == value2 else T)) %>% 
    mutate(x = {{xMetric}}) %>%
    select(linetype, elapsed_sec, x) 
  
  x_breaks <- unique(df$x)
  
  p = df %>% 
    ggplot(aes(x = x, y = elapsed_sec, colour = linetype)) +
    geom_line(size = 1) +
    geom_point() +
    scale_x_continuous(
      breaks =  x_breaks,  
      labels =  x_breaks
    ) +
    scale_y_continuous(
      labels = scales::label_timespan()
    ) +
    theme_minimal() +
    labs(title = paste0("Program time for different ", xString, "s at: "),
         subtitle = filterString,
         x = xString,
         y = "Time elapsed")  +
    coord_cartesian(ylim = c(0,150)) +
    scale_color_manual(values = custom_cols) +
    themeForSaving()
  
  return(p)
}
```


```{r}
p = plotRunTimeFixedValue(15, k, threshold, metric2 = offset, value2 = 15)
plotRunTimeFixedValue(105, threshold, k)


savePlotReport(paste0(gridsearchDir, "test", extType), p)

```